name: 'bwenv Setup'
description: 'Sets up bwenv binary in the GitHub Actions runner'
author: 'titanom'
branding:
  icon: 'box'
  color: 'gray-dark'

inputs:
  version:
    description: 'Version of bwenv to set up. Default is latest.'
    required: false

outputs:
  path:
    description: 'The path to the downloaded bwenv binary'

runs:
  using: 'node20'
  main: 'dist/main.cjs'
